import type { Metadata } from "next";
import localFont from "next/font/local";
import "suneditor/dist/css/suneditor.min.css";
import "../styles/index.scss";
import Navbar from "@/uikits/nav";
import Footer from "@/uikits/footer";
import { MyParticles } from "@/components/particle";

const font1 = localFont({
  src: "./fonts/Montserrat-Bold.ttf",
  variable: "--MontserratBold",
  weight: "900",
});

const font2 = localFont({
  src: "./fonts/Montserrat-Light.ttf",
  variable: "--MontserratLight",
  weight: "100",
});

const font3 = localFont({
  src: "./fonts/Montserrat-Regular.ttf",
  variable: "--MontserratRegular",
  weight: "100",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font1.variable} ${font2.variable}  ${font3.variable}`}
      >
        <Navbar />
        {children}
        <MyParticles />
        <Footer />
      </body>
    </html>
  );
}
